services:
  app:
    image: ghcr.io/rangodj/centralfolio:latest
    build: .
    container_name: centralfolio-app
    ports:
      - "3000:3000"
    volumes:
      - ./snaptrade.db:/app/snaptrade.db
    environment:
      - LOG_LEVEL=info
    restart: unless-stopped
